env:
  global:
    - CIBW_BEFORE_BUILD_LINUX="yum install -y gcc && {pip} install numpy cython"
    - CIBW_TEST_COMMAND="{python} {project}/test/test_tri.py"
    - CIBW_SKIP="cp33-*"
    - TWINE_USERNAME=mikedh

matrix:
  include:
    - dist: trusty
      sudo: required
      language: python
      python: "3.6"
      services:
        - docker
    - os: osx
      osx_image: xcode8.3

install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      brew update;
      brew upgrade python;
    fi
  - pip3 install cibuildwheel==0.6.0

script:
  - cibuildwheel --output-dir wheelhouse
  - python -m pip install twine
  - python -m twine upload wheelhouse/*.whl
