env:
  global:
    - CIBW_TEST_REQUIRES="nose2"
    - CIBW_TEST_COMMAND="cd {project}/test && nose2"
    - CIBW_SKIP="cp33-*"
    - TWINE_USERNAME=mikedh

matrix:
  include:
    - dist: trusty
      env: CIBW_BEFORE_BUILD="yum install -y gcc && pip install numpy cython"
      sudo: required
      language: python
      python: "3.6"
      services:
        - docker
    - os: osx
      osx_image: xcode8.3

install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      brew update;
      brew upgrade python;
    fi
# Install cibuildwheel using pip3 
  - pip3 install cibuildwheel==0.6.0

script:
  - cibuildwheel --output-dir wheelhouse
  - python -m pip install twine
  - python -m twine upload wheelhouse/*.whl
