
env:
  global:
    - CIBW_BEFORE_BUILD="yum install -y gcc && pip install numpy cython"
    - CIBW_TEST_REQUIRES="nose2"
    - CIBW_TEST_COMMAND="cd {project}/test && nose2"
    - CIBW_SKIP="cp33-*"
    - TWINE_USERNAME=mikedh

matrix:
  include:
    - dist: trusty
      sudo: required
      language: python
      python: "3.6"
      services:
        - docker

install:
  # Python 3 is needed to run cibuildwheel 
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      brew install python3;
    fi
# Install cibuildwheel using pip3 to make sure Python 3 is used.
  - pip3 install cibuildwheel==0.6.0

script:
  - cibuildwheel --output-dir wheelhouse
  - python -m pip install twine
  - python -m twine upload wheelhouse/*.whl
